version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    image: payload-app:latest
    ports:
      - '5200:5200'
    environment:
      - NODE_ENV=production
      - PORT=5200
    restart: unless-stopped
    env_file:
      - .env

volumes:
  node_modules:
