services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: payload-app

    restart: unless-stopped

    ports:
      - '5200:5200'

    env_file:
      - .env

    command: node server.js
