/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    pages: Page;
    'home-templates': HomeTemplate;
    'about-templates': AboutTemplate;
    headers: Header;
    footers: Footer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'home-templates': HomeTemplatesSelect<false> | HomeTemplatesSelect<true>;
    'about-templates': AboutTemplatesSelect<false> | AboutTemplatesSelect<true>;
    headers: HeadersSelect<false> | HeadersSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('superadmin' | 'tenant' | 'designer') | null;
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  slug: string;
  smtpUser?: string | null;
  smtpPassword?: string | null;
  domain?: string | null;
  primaryColor?:
    | (
        | 'blue'
        | 'light-blue'
        | 'powder-blue'
        | 'sky-blue'
        | 'gray'
        | 'slate'
        | 'black'
        | 'green'
        | 'emerald'
        | 'teal'
        | 'purple'
        | 'indigo'
        | 'pink'
        | 'rose'
        | 'red'
        | 'orange'
        | 'amber'
      )
    | null;
  secondaryColor?:
    | (
        | 'blue'
        | 'light-blue'
        | 'powder-blue'
        | 'sky-blue'
        | 'gray'
        | 'slate'
        | 'black'
        | 'green'
        | 'emerald'
        | 'teal'
        | 'purple'
        | 'indigo'
        | 'pink'
        | 'rose'
        | 'red'
        | 'orange'
        | 'amber'
      )
    | null;
  fontFamily?:
    | (
        | 'Inter'
        | 'Poppins'
        | 'Roboto'
        | 'Montserrat'
        | 'Outfit'
        | 'DM Sans'
        | 'Open Sans'
        | 'Lato'
        | 'Nunito'
        | 'Playfair Display'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Slug must be unique within the selected tenant
   */
  slug: string;
  templateType: 'home' | 'about' | 'contact' | 'services';
  homeTemplate?: (string | null) | HomeTemplate;
  aboutTemplate?: (string | null) | AboutTemplate;
  content?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            image?: (string | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            features?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (string | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            backgroundColor?: ('primary' | 'secondary' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            media: string | Media;
            imageName?: string | null;
            imageShortDescription?: string | null;
            availabilityText?: string | null;
            relatedText?: string | null;
            position: 'left' | 'right';
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            backgroundColor?: ('white' | 'bg-card') | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlockcontent';
          }
        | CardsWithIcons
        | {
            blockHeading: string;
            headingColor?: ('black' | 'white') | null;
            cards: {
              title: string;
              slug: string;
              image: string | Media;
              description: string;
              cta: {
                text: string;
                link: string;
              };
              id?: string | null;
            }[];
            sectionColor?: ('primary' | 'secondary' | 'bg-soft' | 'bg-dark') | null;
            sectionBackground?: (string | null) | Media;
            columns: '2' | '3' | '4';
            delay?: number | null;
            loading?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'verticleHoverCardsBlock';
          }
        | {
            title: string;
            items: {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | HeroLeftLayoutBlock
        | MapInfoBlockType
        | {
            slides: {
              image: string | Media;
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            slidesPerMobile?: number | null;
            slidesPerTablet?: number | null;
            slidesPerDesktop?: number | null;
            autoplay?: boolean | null;
            delay?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carouselBlock';
          }
        | {
            slides: {
              image: string | Media;
              name: string;
              designation?: string | null;
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              ctaButtons?:
                | {
                    label: string;
                    url: string;
                    newTab?: boolean | null;
                    style?: ('primary' | 'secondary') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            slidesPerMobile?: number | null;
            slidesPerTablet?: number | null;
            slidesPerDesktop?: number | null;
            autoplay?: boolean | null;
            delay?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamCarousalBlock';
          }
      )[]
    | null;
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-templates".
 */
export interface HomeTemplate {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Predefined blocks structure for this template
   */
  blocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            image?: (string | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            features?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (string | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            backgroundColor?: ('primary' | 'secondary' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            media: string | Media;
            imageName?: string | null;
            imageShortDescription?: string | null;
            availabilityText?: string | null;
            relatedText?: string | null;
            position: 'left' | 'right';
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            backgroundColor?: ('white' | 'bg-card') | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlockcontent';
          }
        | {
            title: string;
            items: {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | CardsWithIcons
        | {
            blockHeading: string;
            headingColor?: ('black' | 'white') | null;
            cards: {
              title: string;
              slug: string;
              image: string | Media;
              description: string;
              cta: {
                text: string;
                link: string;
              };
              id?: string | null;
            }[];
            sectionColor?: ('primary' | 'secondary' | 'bg-soft' | 'bg-dark') | null;
            sectionBackground?: (string | null) | Media;
            columns: '2' | '3' | '4';
            delay?: number | null;
            loading?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'verticleHoverCardsBlock';
          }
        | HeroLeftLayoutBlock
        | MapInfoBlockType
        | {
            slides: {
              image: string | Media;
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            slidesPerMobile?: number | null;
            slidesPerTablet?: number | null;
            slidesPerDesktop?: number | null;
            autoplay?: boolean | null;
            delay?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carouselBlock';
          }
        | {
            slides: {
              image: string | Media;
              name: string;
              designation?: string | null;
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              ctaButtons?:
                | {
                    label: string;
                    url: string;
                    newTab?: boolean | null;
                    style?: ('primary' | 'secondary') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            slidesPerMobile?: number | null;
            slidesPerTablet?: number | null;
            slidesPerDesktop?: number | null;
            autoplay?: boolean | null;
            delay?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamCarousalBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsWithIcons".
 */
export interface CardsWithIcons {
  blockHeading: string;
  columns?: number | null;
  cards: {
    icon?: (string | null) | Media;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    gradientFrom?: ('primary' | 'secondary' | 'gray' | 'white') | null;
    gradientTo?: ('primary' | 'secondary' | 'gray' | 'white') | null;
    gradientDirection?: ('to-r' | 'to-l' | 'to-b' | 'to-t' | 'radial') | null;
    solidBg?: ('white' | 'primary' | 'secondary' | 'gray') | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardsWithIcons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroLeftLayoutBlock".
 */
export interface HeroLeftLayoutBlock {
  backgroundImage: string | Media;
  overlayOpacity?: number | null;
  tag?: string | null;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  buttons?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroLeftLayoutBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapInfoBlockType".
 */
export interface MapInfoBlockType {
  title?: string | null;
  /**
   * Full clinic address
   */
  address: string;
  /**
   * Google Maps direct link (used for the Location button)
   */
  googleMapLink: string;
  /**
   * Google Maps Embed iframe URL
   */
  mapEmbedUrl: string;
  phone: string;
  email: string;
  parking?: boolean | null;
  accessibility?: boolean | null;
  officeHoursSection: {
    officetitle: string;
    officeHours?:
      | {
          day: string;
          time: string;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapInfoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-templates".
 */
export interface AboutTemplate {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Predefined blocks structure for this template
   */
  blocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            image?: (string | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            features?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (string | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            backgroundColor?: ('primary' | 'secondary' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers".
 */
export interface Header {
  id: string;
  name: string;
  tenant?: (string | null) | Tenant;
  layout: (
    | {
        logo?: (string | null) | Media;
        menuItems?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        showButton?: boolean | null;
        buttonLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'headerSimple';
      }
    | {
        logo?: (string | null) | Media;
        announcementText?: string | null;
        menuItems?:
          | {
              label?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'headerCentered';
      }
    | {
        logo?: (string | null) | Media;
        navItems?:
          | {
              label: string;
              icon?: (string | null) | Media;
              page?: (string | null) | Page;
              customUrl?: string | null;
              children?:
                | {
                    label: string;
                    icon?: (string | null) | Media;
                    page?: (string | null) | Page;
                    customUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        headerStyle: 'default' | 'modern' | 'centered';
        ctas?:
          | {
              label: string;
              link?: (string | null) | Page;
              customUrl?: string | null;
              style?: ('primary' | 'secondary' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'headerCTA';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: string;
  name: string;
  tenant?: (string | null) | Tenant;
  layout: (
    | {
        copyrightText?: string | null;
        socialLinks?:
          | {
              platform?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'footerSimple';
      }
    | {
        columns?:
          | {
              title?: string | null;
              links?:
                | {
                    label?: string | null;
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'footerColumns';
      }
    | {
        enableI18n?: boolean | null;
        backgroundImage?: (string | null) | Media;
        description?: string | null;
        ctaButton?: {
          text?: string | null;
          link?: (string | null) | Page;
        };
        socialLinks?:
          | {
              platform?: ('facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube') | null;
              url: string;
              id?: string | null;
            }[]
          | null;
        hours?:
          | {
              day?: string | null;
              time?: string | null;
              id?: string | null;
            }[]
          | null;
        mapEmbed?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'footerNewsletter';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'home-templates';
        value: string | HomeTemplate;
      } | null)
    | ({
        relationTo: 'about-templates';
        value: string | AboutTemplate;
      } | null)
    | ({
        relationTo: 'headers';
        value: string | Header;
      } | null)
    | ({
        relationTo: 'footers';
        value: string | Footer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  smtpUser?: T;
  smtpPassword?: T;
  domain?: T;
  primaryColor?: T;
  secondaryColor?: T;
  fontFamily?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  templateType?: T;
  homeTemplate?: T;
  aboutTemplate?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              ctaText?: T;
              ctaLink?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlockcontent?:
          | T
          | {
              media?: T;
              imageName?: T;
              imageShortDescription?: T;
              availabilityText?: T;
              relatedText?: T;
              position?: T;
              content?: T;
              backgroundColor?: T;
              padding?: T;
              id?: T;
              blockName?: T;
            };
        cardsWithIcons?: T | CardsWithIconsSelect<T>;
        verticleHoverCardsBlock?:
          | T
          | {
              blockHeading?: T;
              headingColor?: T;
              cards?:
                | T
                | {
                    title?: T;
                    slug?: T;
                    image?: T;
                    description?: T;
                    cta?:
                      | T
                      | {
                          text?: T;
                          link?: T;
                        };
                    id?: T;
                  };
              sectionColor?: T;
              sectionBackground?: T;
              columns?: T;
              delay?: T;
              loading?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroLeftLayoutBlock?: T | HeroLeftLayoutBlockSelect<T>;
        mapInfoBlock?: T | MapInfoBlockTypeSelect<T>;
        carouselBlock?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    content?: T;
                    id?: T;
                  };
              slidesPerMobile?: T;
              slidesPerTablet?: T;
              slidesPerDesktop?: T;
              autoplay?: T;
              delay?: T;
              id?: T;
              blockName?: T;
            };
        teamCarousalBlock?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    name?: T;
                    designation?: T;
                    content?: T;
                    ctaButtons?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              slidesPerMobile?: T;
              slidesPerTablet?: T;
              slidesPerDesktop?: T;
              autoplay?: T;
              delay?: T;
              id?: T;
              blockName?: T;
            };
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsWithIcons_select".
 */
export interface CardsWithIconsSelect<T extends boolean = true> {
  blockHeading?: T;
  columns?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        gradientFrom?: T;
        gradientTo?: T;
        gradientDirection?: T;
        solidBg?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroLeftLayoutBlock_select".
 */
export interface HeroLeftLayoutBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  overlayOpacity?: T;
  tag?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapInfoBlockType_select".
 */
export interface MapInfoBlockTypeSelect<T extends boolean = true> {
  title?: T;
  address?: T;
  googleMapLink?: T;
  mapEmbedUrl?: T;
  phone?: T;
  email?: T;
  parking?: T;
  accessibility?: T;
  officeHoursSection?:
    | T
    | {
        officetitle?: T;
        officeHours?:
          | T
          | {
              day?: T;
              time?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-templates_select".
 */
export interface HomeTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              ctaText?: T;
              ctaLink?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlockcontent?:
          | T
          | {
              media?: T;
              imageName?: T;
              imageShortDescription?: T;
              availabilityText?: T;
              relatedText?: T;
              position?: T;
              content?: T;
              backgroundColor?: T;
              padding?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardsWithIcons?: T | CardsWithIconsSelect<T>;
        verticleHoverCardsBlock?:
          | T
          | {
              blockHeading?: T;
              headingColor?: T;
              cards?:
                | T
                | {
                    title?: T;
                    slug?: T;
                    image?: T;
                    description?: T;
                    cta?:
                      | T
                      | {
                          text?: T;
                          link?: T;
                        };
                    id?: T;
                  };
              sectionColor?: T;
              sectionBackground?: T;
              columns?: T;
              delay?: T;
              loading?: T;
              id?: T;
              blockName?: T;
            };
        heroLeftLayoutBlock?: T | HeroLeftLayoutBlockSelect<T>;
        mapInfoBlock?: T | MapInfoBlockTypeSelect<T>;
        carouselBlock?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    content?: T;
                    id?: T;
                  };
              slidesPerMobile?: T;
              slidesPerTablet?: T;
              slidesPerDesktop?: T;
              autoplay?: T;
              delay?: T;
              id?: T;
              blockName?: T;
            };
        teamCarousalBlock?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    name?: T;
                    designation?: T;
                    content?: T;
                    ctaButtons?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              slidesPerMobile?: T;
              slidesPerTablet?: T;
              slidesPerDesktop?: T;
              autoplay?: T;
              delay?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-templates_select".
 */
export interface AboutTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              ctaText?: T;
              ctaLink?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers_select".
 */
export interface HeadersSelect<T extends boolean = true> {
  name?: T;
  tenant?: T;
  layout?:
    | T
    | {
        headerSimple?:
          | T
          | {
              logo?: T;
              menuItems?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              showButton?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        headerCentered?:
          | T
          | {
              logo?: T;
              announcementText?: T;
              menuItems?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        headerCTA?:
          | T
          | {
              logo?: T;
              navItems?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    page?: T;
                    customUrl?: T;
                    children?:
                      | T
                      | {
                          label?: T;
                          icon?: T;
                          page?: T;
                          customUrl?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              headerStyle?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    link?: T;
                    customUrl?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  name?: T;
  tenant?: T;
  layout?:
    | T
    | {
        footerSimple?:
          | T
          | {
              copyrightText?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        footerColumns?:
          | T
          | {
              columns?:
                | T
                | {
                    title?: T;
                    links?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        footerNewsletter?:
          | T
          | {
              enableI18n?: T;
              backgroundImage?: T;
              description?: T;
              ctaButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              hours?:
                | T
                | {
                    day?: T;
                    time?: T;
                    id?: T;
                  };
              mapEmbed?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
